// <auto-generated />
using System;
using BelleMariee.App.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BelleMariee.App.DataAccess.Migrations
{
    [DbContext(typeof(BelleDbContext))]
    [Migration("20240719140735_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BelleMariee.App.DataAccess.Identity.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("BelleMariee.App.DataAccess.Identity.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(4978),
                            IsDeleted = false,
                            Name = "After"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(4980),
                            IsDeleted = false,
                            Name = "AKesim"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(4981),
                            IsDeleted = false,
                            Name = "Balık"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(4982),
                            IsDeleted = false,
                            Name = "Helen"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(4983),
                            IsDeleted = false,
                            Name = "Modern"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5062),
                            IsDeleted = false,
                            Name = "Nikah"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5063),
                            IsDeleted = false,
                            Name = "Prenses"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5064),
                            IsDeleted = false,
                            Name = "UzunK"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5064),
                            IsDeleted = false,
                            Name = "Buket"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5065),
                            IsDeleted = false,
                            Name = "Duvak"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5066),
                            IsDeleted = false,
                            Name = "Tac"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5067),
                            IsDeleted = false,
                            Name = "Ayakkabı"
                        });
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("/images/product/default1.jpg");

                    b.Property<string>("ImageUrl2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5102),
                            Description = "CARNELIAN\r\nÜrün Kodu:\r\n4XLWBM1870W",
                            ImageUrl = "/images/product/after1.1.webp",
                            ImageUrl2 = "/images/product/after1.2.webp",
                            ImageUrl3 = "/images/product/after3.3.webp",
                            IsDeleted = false,
                            Name = "Tek Omuzlu After Party Elbisesi",
                            Price = 5000m,
                            ProductTypeId = 1,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5110),
                            Description = "Ürün Kodu:\r\nWHT0002TR|WH",
                            ImageUrl = "/images/product/after2.1.webp",
                            ImageUrl2 = "/images/product/after2.2.webp",
                            ImageUrl3 = "/images/product/after2.3.webp",
                            IsDeleted = false,
                            Name = "Straplez After Party Elbisesi",
                            Price = 9000m,
                            ProductTypeId = 1,
                            Size = "40",
                            Stock = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5113),
                            Description = "Ürün Kodu:\r\nWHT00AAH",
                            ImageUrl = "/images/product/default1.jpg",
                            ImageUrl2 = "/images/product/default2.jpg",
                            ImageUrl3 = "/images/product/default3.jpg",
                            IsDeleted = false,
                            Name = "Askılı After Party Elbisesi",
                            Price = 7000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5115),
                            Description = "Ürün Kodu:\r\n4XLSWG989|SOLID/IV_38",
                            ImageUrl = "/images/product/AKesim1.1.webp",
                            ImageUrl2 = "/images/product/AKesim1.2.webp",
                            ImageUrl3 = "/images/product/AKesim1.3.webp",
                            IsDeleted = false,
                            Name = "A Kesim Kol Detaylı Gelinlik",
                            Price = 38000m,
                            ProductTypeId = 1,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5117),
                            Description = "Ürün Kodu:\r\n4XLSWG76557ID/I8",
                            ImageUrl = "/images/product/AKesim2.1.webp",
                            ImageUrl2 = "/images/product/AKesim2.2.webp",
                            ImageUrl3 = "/images/product/AKesim2.3.webp",
                            IsDeleted = false,
                            Name = "A Kesim Tül Detaylı Gelinlik",
                            Price = 39000m,
                            ProductTypeId = 1,
                            Size = "40",
                            Stock = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5119),
                            Description = "Ürün Kodu:\r\n4XRHDZTX8",
                            ImageUrl = "/images/product/AKesim3.1.webp",
                            ImageUrl2 = "/images/product/AKesim3.2.webp",
                            ImageUrl3 = "/images/product/AKesim3.3.webp",
                            IsDeleted = false,
                            Name = "A Kesim Straplez Gelinlik",
                            Price = 41000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5121),
                            Description = "Ürün Kodu:\r\nSWGHBFHD38",
                            ImageUrl = "/images/product/balık1.1.webp",
                            ImageUrl2 = "/images/product/balık1.2.webp",
                            ImageUrl3 = "/images/product/balık1.3.webp",
                            IsDeleted = false,
                            Name = "V Yaka Balık Model Gelinlik",
                            Price = 42000m,
                            ProductTypeId = 1,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5123),
                            Description = "Ürün Kodu:\r\nSWG970|SOLID/IV_38",
                            ImageUrl = "/images/product/balık2.1.webp",
                            ImageUrl2 = "/images/product/balık2.2.webp",
                            ImageUrl3 = "/images/product/balık2.3.webp",
                            IsDeleted = false,
                            Name = "Straplez Balık ModelGelinlik",
                            Price = 43000m,
                            ProductTypeId = 1,
                            Size = "40",
                            Stock = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5125),
                            Description = "Ürün Kodu:\r\nSWFHFHHGS38",
                            ImageUrl = "/images/product/balık3.1.webp",
                            ImageUrl2 = "/images/product/balık3.2.webp",
                            ImageUrl3 = "/images/product/balık3.3.webp",
                            IsDeleted = false,
                            Name = "Straplez Balık Model Gelinlik",
                            Price = 44000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5128),
                            Description = "AMELIE\r\nÜrün Kodu:\r\n1028|KEMİK_40",
                            ImageUrl = "/images/product/helen1.1.webp",
                            ImageUrl2 = "/images/product/helen1.2.webp",
                            ImageUrl3 = "/images/product/helen1.3.webp",
                            IsDeleted = false,
                            Name = "Derin Yırtmaçlı Sırt Detaylı Gelinlik",
                            Price = 35000m,
                            ProductTypeId = 1,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5130),
                            Description = "CAMILLA\r\nÜrün Kodu:\r\n1020|KEMİK_40",
                            ImageUrl = "/images/product/helen2.1.webp",
                            ImageUrl2 = "/images/product/helen2.2.webp",
                            ImageUrl3 = "/images/product/helen2.3.webp",
                            IsDeleted = false,
                            Name = "V Yaka Payet İşlemeli Gelinlik",
                            Price = 36000m,
                            ProductTypeId = 1,
                            Size = "40",
                            Stock = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5132),
                            Description = "EDITH\r\nÜrün Kodu:\r\n1029|KEMİK_40",
                            ImageUrl = "/images/product/helen3.1.webp",
                            ImageUrl2 = "/images/product/helen3.2.webp",
                            ImageUrl3 = "/images/product/helen3.3.webp",
                            IsDeleted = false,
                            Name = "Düşük Omuzlu Büzgülü Kol Detaylı Gelinlik",
                            Price = 37000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5134),
                            Description = "Gelinlik\r\nÜrün Kodu:\r\n4XLSDWG1052|SOFT WHITE_40",
                            ImageUrl = "/images/product/Modern1.1.webp",
                            ImageUrl2 = "/images/product/Modern1.2.webp",
                            ImageUrl3 = "/images/product/dModern1.3.webp",
                            IsDeleted = false,
                            Name = "Önü Kısa Arkası Uzun Krep Dar Kesim",
                            Price = 46000m,
                            ProductTypeId = 1,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5136),
                            Description = "HARMONIA\r\nÜrün Kodu:\r\n4XLWPD26986|IVORY_38",
                            ImageUrl = "/images/product/Modern2.1.webp",
                            ImageUrl2 = "/images/product/Modern2.2.webp",
                            ImageUrl3 = "/images/product/Modern2.3.webp",
                            IsDeleted = false,
                            Name = "Fiyonk Detaylı Saten Dar Kesim Gelinlik",
                            Price = 47000m,
                            ProductTypeId = 1,
                            Size = "40",
                            Stock = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5138),
                            Description = "CARINO\r\nÜrün Kodu:\r\n1017|KEMİK_40",
                            ImageUrl = "/images/product/Modern3.1.webp",
                            ImageUrl2 = "/images/product/Modern3.2.webp",
                            ImageUrl3 = "/images/product/Modern3.3.webp",
                            IsDeleted = false,
                            Name = "Boncuk İşlemeli Kuyruklu Gelinlik",
                            Price = 48000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5140),
                            Description = "Ürün Kodu:\r\nMA-B5625-001-INF|A29_0",
                            ImageUrl = "/images/product/nikah1.1.webp",
                            ImageUrl2 = "/images/product/nikah1.2.webp",
                            ImageUrl3 = "/images/product/nikah1.3.webp",
                            IsDeleted = false,
                            Name = "Yırtmaçlı Midi Boy Jarse Nikah Elbisesi",
                            Price = 31000m,
                            ProductTypeId = 1,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5142),
                            Description = "Ürün Kodu:\r\nVC5595WHT|IVORY_34",
                            ImageUrl = "/images/product/nkah2.1.webp",
                            ImageUrl2 = "/images/product/nikah2.2.webp",
                            ImageUrl3 = "/images/product/nikah2.3.webp",
                            IsDeleted = false,
                            Name = "Arkası Yırtmaçlı Balon Kol Detaylı Gelinlik",
                            Price = 32000m,
                            ProductTypeId = 1,
                            Size = "40",
                            Stock = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5144),
                            Description = "Ürün Kodu:\r\nVC5592WHT|IVORY_34",
                            ImageUrl = "/images/product/nikah3.1.webp",
                            ImageUrl2 = "/images/product/nikah3.2.webp",
                            ImageUrl3 = "/images/product/nikah3.3.webp",
                            IsDeleted = false,
                            Name = "Fiyonk Detaylı Yırtmaçlı Krep Gelinlik",
                            Price = 33000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5146),
                            Description = " ÜRÜN KODU: 34066 700GG",
                            ImageUrl = "/images/product/prenses1.1.webp",
                            ImageUrl2 = "/images/product/prenses1.2.webp",
                            ImageUrl3 = "/images/product/prenses1.3.webp",
                            IsDeleted = false,
                            Name = "Dantel İşlemeli Straplez Balo Tipi Kuyruklu Gelinlik",
                            Price = 49000m,
                            ProductTypeId = 1,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5148),
                            Description = " ÜRÜN KODU: 34067 701GG",
                            ImageUrl = "/images/product/prenses2.1.webp",
                            ImageUrl2 = "/images/product/prenses2.2.webp",
                            ImageUrl3 = "/images/product/prenses2.3.webp",
                            IsDeleted = false,
                            Name = "İnci İşlemeli Askılı A Kesim Gelinlik",
                            Price = 50000m,
                            ProductTypeId = 1,
                            Size = "40",
                            Stock = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5150),
                            Description = " ÜRÜN KODU: 34068 702GG",
                            ImageUrl = "/images/product/prenses3.1.webp",
                            ImageUrl2 = "/images/product/prenses3.2.webp",
                            ImageUrl3 = "/images/product/prenses3.3.webp",
                            IsDeleted = false,
                            Name = "Saten Dantel İşlemeli V Yaka Gelinlik",
                            Price = 51000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5152),
                            Description = "FRANCESCA\r\nÜrün Kodu:\r\n4XLWPD30119|IVORY/OLEG_42",
                            ImageUrl = "/images/product/uzunk1.1.webp",
                            ImageUrl2 = "/images/product/uzunk1.2.webp",
                            ImageUrl3 = "/images/product/uzunk1.3.webp",
                            IsDeleted = false,
                            Name = "Düşük Omuzlu Uzun Kollu Dar Kesim Gelinlik",
                            Price = 34000m,
                            ProductTypeId = 1,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5154),
                            Description = "NORA\r\nÜrün Kodu:\r\n4XLMS251270|IVORY/STON_40",
                            ImageUrl = "/images/product/uzunk2.1.webp",
                            ImageUrl2 = "/images/product/uzunk2.2.webp",
                            ImageUrl3 = "/images/product/uzunk2.3.webp",
                            IsDeleted = false,
                            Name = "Uzun Kollu Dar Kesim Gelinlik",
                            Price = 35000m,
                            ProductTypeId = 1,
                            Size = "40",
                            Stock = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5156),
                            Description = "VALENTINA\r\nÜrün Kodu:\r\n4XLWPD30203|IVORY/N N_42",
                            ImageUrl = "/images/product/uzunk3.1.webp",
                            ImageUrl2 = "/images/product/uzunk3.2.webp",
                            ImageUrl3 = "/images/product/uzunk3.3.webp",
                            IsDeleted = false,
                            Name = "Uzun Kollu Işıltılı Tül Dar Kesim Gelinlik",
                            Price = 36000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5158),
                            Description = "Buket 1 Aksesuar, ÜRÜN KODU: 45001 800AK",
                            ImageUrl = "/images/product/b1.1.webp",
                            ImageUrl2 = "/images/product/b1.2.webp",
                            ImageUrl3 = "/images/product/b1.3.webp",
                            IsDeleted = false,
                            Name = "GRAND MAGNOLIA",
                            Price = 2000m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 10,
                            UserId = 0
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5160),
                            Description = "Buket 2 Aksesuar, ÜRÜN KODU: 45002 801AK",
                            ImageUrl = "/images/product/b2.1.webp",
                            ImageUrl2 = "/images/product/b2.2.webp",
                            ImageUrl3 = "/images/product/b2.3.webp",
                            IsDeleted = false,
                            Name = "GLORIA",
                            Price = 2500m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 8,
                            UserId = 0
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5164),
                            Description = "Buket 3 Aksesuar, ÜRÜN KODU: 45003 802AK",
                            ImageUrl = "/images/product/b3.1.webp",
                            ImageUrl2 = "/images/product/b3.2.webp",
                            ImageUrl3 = "/images/product/b3.3.webp",
                            IsDeleted = false,
                            Name = "ECROU",
                            Price = 3000m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 6,
                            UserId = 0
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5166),
                            Description = "Buket 4 Aksesuar, ÜRÜN KODU: 45004 803AK",
                            ImageUrl = "/images/product/b4.1.webp",
                            ImageUrl2 = "/images/product/b4.2.webp",
                            ImageUrl3 = "/images/product/b4.3.webp",
                            IsDeleted = false,
                            Name = "SPRING",
                            Price = 2200m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 12,
                            UserId = 0
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5168),
                            Description = "Buket 5 Aksesuar, ÜRÜN KODU: 45005 804AK",
                            ImageUrl = "/images/product/b5.1.webp",
                            ImageUrl2 = "/images/product/b5.2.webp",
                            ImageUrl3 = "/images/product/b5.3.webp",
                            IsDeleted = false,
                            Name = "MÜRDÜM",
                            Price = 2700m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 9,
                            UserId = 0
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5169),
                            Description = "Buket 6 Aksesuar, ÜRÜN KODU: 45006 805AK",
                            ImageUrl = "/images/product/b6.1.webp",
                            ImageUrl2 = "/images/product/b6.2.webp",
                            ImageUrl3 = "/images/product/b6.3.webp",
                            IsDeleted = false,
                            Name = "V E L V E T",
                            Price = 2900m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 7,
                            UserId = 0
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5171),
                            Description = "Ürün Kodu:\r\nWPD27227|IVORY_U",
                            ImageUrl = "/images/product/duvak1.1.webp",
                            ImageUrl2 = "/images/product/duvak1.2.webp",
                            ImageUrl3 = "/images/product/duvak1.3.webp",
                            IsDeleted = false,
                            Name = "Dantel ve Pul İşlemeli Katedral Boy Gelin Duvağı",
                            Price = 1500m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 10,
                            UserId = 0
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5173),
                            Description = "Ürün Kodu:\r\nINCILIDUVAKV2|IVORY_U",
                            ImageUrl = "/images/product/duvak2.1",
                            ImageUrl2 = "/images/product/duvak2.2.webp",
                            ImageUrl3 = "/images/product/duvak2.3.webp",
                            IsDeleted = false,
                            Name = "Uzun Tül Tamamı İnci Detaylı Duvak",
                            Price = 2000m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 8,
                            UserId = 0
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5175),
                            Description = "Ürün Kodu:\r\nWPD28215V2|IVORY_U",
                            ImageUrl = "/images/product/duvak3.1.webp",
                            ImageUrl2 = "/images/product/duvak3.2.webp",
                            ImageUrl3 = "/images/product/duvak3.3.webp",
                            IsDeleted = false,
                            Name = "Taş İşlemeli Kısa Duvak",
                            Price = 2500m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 6,
                            UserId = 0
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5177),
                            Description = "Ürün Kodu:\r\nV1810B|IVORY_U",
                            ImageUrl = "/images/product/duvak4.1.webp",
                            ImageUrl2 = "/images/product/duvak4.2.webp",
                            ImageUrl3 = "/images/product/duvak4.3.webp",
                            IsDeleted = false,
                            Name = "Çiçek Motif Dantel İşlemeli Tül Gelin Duvağı",
                            Price = 2500m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 6,
                            UserId = 0
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 11,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5180),
                            Description = "Ürün Kodu:\r\nVGR191101001|IVORY_U",
                            ImageUrl = "/images/product/tac1.1.webp",
                            ImageUrl2 = "/images/product/tac1.2.webp",
                            ImageUrl3 = "/images/product/tac1.3.webp",
                            IsDeleted = false,
                            Name = "Kırık Beyaz İncili Gelin Tacı",
                            Price = 1700m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 7,
                            UserId = 0
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 11,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5181),
                            Description = "Ürün Kodu:\r\nH42235|SILVER_U",
                            ImageUrl = "/images/product/tac2.1.webp",
                            ImageUrl2 = "/images/product/tac2.2.webp",
                            ImageUrl3 = "/images/product/tac2.3.webp",
                            IsDeleted = false,
                            Name = "Yapay Elmas Gelin Tacı",
                            Price = 2100m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 8,
                            UserId = 0
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 11,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5183),
                            Description = "Ürün Kodu:\r\nWPD20601|IVORY_U",
                            ImageUrl = "/images/product/tac3.1.webp",
                            ImageUrl2 = "/images/product/tac3.2.webp",
                            ImageUrl3 = "/images/product/tac3.3.webp",
                            IsDeleted = false,
                            Name = "İnci Detaylı Yapay Elmas Gelin Tacı",
                            Price = 200m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 6,
                            UserId = 0
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 12,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5186),
                            Description = "ÜRÜN KODU : 35060 206G",
                            ImageUrl = "/images/product/1.1.jpg",
                            ImageUrl2 = "/images/product/1.2.jpg",
                            ImageUrl3 = "/images/product/1.3.jpg",
                            IsDeleted = false,
                            Name = "SEDEF SATEN BLOOM GELİN AYAKKABISI",
                            Price = 2850m,
                            ProductTypeId = 3,
                            Size = "36",
                            Stock = 6,
                            UserId = 0
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 12,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5188),
                            Description = "ÜRÜN KODU : 35060 0250G\r\n",
                            ImageUrl = "/images/product/2.1.jpg",
                            ImageUrl2 = "/images/product/2.2.jpg",
                            ImageUrl3 = "/images/product/2.3.jpg",
                            IsDeleted = false,
                            Name = "SEDEF SATEN FLORENCE MİNİ TOPUK GELİN AYAKKABISI\r\n",
                            Price = 4500m,
                            ProductTypeId = 3,
                            Size = "37",
                            Stock = 9,
                            UserId = 0
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 12,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5190),
                            Description = "ÜRÜN KODU : 34210 2233G",
                            ImageUrl = "/images/product/3.1.jpg",
                            ImageUrl2 = "/images/product/3.2.jpg",
                            ImageUrl3 = "/images/product/3.3.jpg",
                            IsDeleted = false,
                            Name = "SEDEF NİNA İNCE TOPUK GELİN AYAKKABISI\r\n",
                            Price = 4500m,
                            ProductTypeId = 3,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 12,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5192),
                            Description = "ÜRÜN KODU : 35072 1159G\r\n",
                            ImageUrl = "/images/product/4.1.jpg",
                            ImageUrl2 = "/images/product/4.2.jpg",
                            ImageUrl3 = "/images/product/4.3.jpg",
                            IsDeleted = false,
                            Name = "SEDEF SATEN LEROY TEK BANT GELİN AYAKKABISI\r\n",
                            Price = 2250m,
                            ProductTypeId = 3,
                            Size = "39",
                            Stock = 7,
                            UserId = 0
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 12,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5195),
                            Description = "ÜRÜN KODU : 34066 700GG\r\n",
                            ImageUrl = "/images/product/5.1.jpg",
                            ImageUrl2 = "/images/product/5.2.jpg",
                            ImageUrl3 = "/images/product/5.3.jpg",
                            IsDeleted = false,
                            Name = "SEDEF SO VERA GELİN AYAKKABISI\r\n",
                            Price = 4500m,
                            ProductTypeId = 3,
                            Size = "40",
                            Stock = 6,
                            UserId = 0
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 12,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(5202),
                            Description = "ÜRÜN KODU : 35060 202G\r\n",
                            ImageUrl = "/images/product/6.1.jpg",
                            ImageUrl2 = "/images/product/6.2.jpg",
                            ImageUrl3 = "/images/product/6.3.jpg",
                            IsDeleted = false,
                            Name = "SEDEF SATEN BLOOM GELİN AYAKKABISI\r\n",
                            Price = 2850m,
                            ProductTypeId = 3,
                            Size = "41",
                            Stock = 7,
                            UserId = 0
                        });
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.ProductSaleDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("ProductSaleDetails");
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(4610),
                            IsDeleted = false,
                            Name = "Gow"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(4640),
                            IsDeleted = false,
                            Name = "Accessory"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 7, 19, 17, 7, 34, 33, DateTimeKind.Local).AddTicks(4642),
                            IsDeleted = false,
                            Name = "Shoe"
                        });
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Product", b =>
                {
                    b.HasOne("BelleMariee.App.Entity.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelleMariee.App.Entity.Entities.ProductType", null)
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.ProductSaleDetails", b =>
                {
                    b.HasOne("BelleMariee.App.Entity.Entities.Product", "Product")
                        .WithMany("ProductSalesDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelleMariee.App.Entity.Entities.Sale", "ProductSale")
                        .WithMany("ProductSalesDetails")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductSale");
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Sale", b =>
                {
                    b.HasOne("BelleMariee.App.Entity.Entities.Customer", "Customer")
                        .WithMany("ProductSales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("BelleMariee.App.DataAccess.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BelleMariee.App.DataAccess.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BelleMariee.App.DataAccess.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("BelleMariee.App.DataAccess.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelleMariee.App.DataAccess.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BelleMariee.App.DataAccess.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Customer", b =>
                {
                    b.Navigation("ProductSales");
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Product", b =>
                {
                    b.Navigation("ProductSalesDetails");
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Sale", b =>
                {
                    b.Navigation("ProductSalesDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
