// <auto-generated />
using System;
using BelleMariee.App.DataAccess.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BelleMariee.App.DataAccess.Migrations
{
    [DbContext(typeof(BelleDbContext))]
    partial class BelleDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BelleMariee.App.DataAccess.Identity.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("BelleMariee.App.DataAccess.Identity.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(302),
                            IsDeleted = false,
                            Name = "After"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(308),
                            IsDeleted = false,
                            Name = "AKesim"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(309),
                            IsDeleted = false,
                            Name = "Balık"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(310),
                            IsDeleted = false,
                            Name = "Helen"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(312),
                            IsDeleted = false,
                            Name = "Modern"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(313),
                            IsDeleted = false,
                            Name = "Nikah"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(314),
                            IsDeleted = false,
                            Name = "Prenses"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(315),
                            IsDeleted = false,
                            Name = "UzunK"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(316),
                            IsDeleted = false,
                            Name = "Buket"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(317),
                            IsDeleted = false,
                            Name = "Duvak"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(318),
                            IsDeleted = false,
                            Name = "Tac"
                        },
                        new
                        {
                            Id = 12,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(319),
                            IsDeleted = false,
                            Name = "Ayakkabı"
                        });
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("/images/product/default1.jpg");

                    b.Property<string>("ImageUrl2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(439),
                            Description = "CARNELIAN\r\nÜrün Kodu:\r\n4XLWBM1870W",
                            ImageUrl = "/images/product/after1.1.webp",
                            ImageUrl2 = "/images/product/after1.2.webp",
                            ImageUrl3 = "/images/product/after3.3.webp",
                            IsDeleted = false,
                            Name = "Tek Omuzlu After Party Elbisesi",
                            Price = 5000m,
                            ProductTypeId = 1,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(449),
                            Description = "Ürün Kodu:\r\nWHT0002TR|WH",
                            ImageUrl = "/images/product/after2.1.webp",
                            ImageUrl2 = "/images/product/after2.2.webp",
                            ImageUrl3 = "/images/product/after2.3.webp",
                            IsDeleted = false,
                            Name = "Straplez After Party Elbisesi",
                            Price = 9000m,
                            ProductTypeId = 1,
                            Size = "40",
                            Stock = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(453),
                            Description = "Ürün Kodu:\r\nWHT00AAH",
                            ImageUrl = "/images/product/after3.1.webp",
                            ImageUrl2 = "/images/product/after3.2.webp",
                            ImageUrl3 = "/images/product/after3.3.webp",
                            IsDeleted = false,
                            Name = "Askılı After Party Elbisesi",
                            Price = 7000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(455),
                            Description = "Ürün Kodu:\r\nWHT0009TR|WHITE_34",
                            ImageUrl = "/images/product/after4.1.webp",
                            ImageUrl2 = "/images/product/after4.2.webp",
                            ImageUrl3 = "/images/product/after4.3.webp",
                            IsDeleted = false,
                            Name = "Beyaz Düşük Balon Kollu Tafta Mini Gelinlik",
                            Price = 42000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(457),
                            Description = "Ürün Kodu:\r\nWHT0015TR|WHITE_34",
                            ImageUrl = "/images/product/after5.1.webp",
                            ImageUrl2 = "/images/product/after5.2.webp",
                            ImageUrl3 = "/images/product/after5.3.webp",
                            IsDeleted = false,
                            Name = "Beyaz Uzun Tül Kollu Jarse Mini Nikah Elbisesi",
                            Price = 42000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(459),
                            Description = "Ürün Kodu:\r\nMA-B5617-001-INF|A29_0",
                            ImageUrl = "/images/product/after6.1.webp",
                            ImageUrl2 = "/images/product/after6.2.webp",
                            ImageUrl3 = "/images/product/after6.3.webp",
                            IsDeleted = false,
                            Name = "Yırtmaçlı Saten Uzun Abiye Gelinlik",
                            Price = 42000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(513),
                            Description = "Ürün Kodu:\r\n4XLSWG989|SOLID/IV_38",
                            ImageUrl = "/images/product/AKesim1.1.webp",
                            ImageUrl2 = "/images/product/AKesim1.2.webp",
                            ImageUrl3 = "/images/product/AKesim1.3.webp",
                            IsDeleted = false,
                            Name = "A Kesim Kol Detaylı Gelinlik",
                            Price = 38000m,
                            ProductTypeId = 1,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(516),
                            Description = "Ürün Kodu:\r\n4XLSWG76557ID/I8",
                            ImageUrl = "/images/product/AKesim2.1.webp",
                            ImageUrl2 = "/images/product/AKesim2.2.webp",
                            ImageUrl3 = "/images/product/AKesim2.3.webp",
                            IsDeleted = false,
                            Name = "A Kesim Tül Detaylı Gelinlik",
                            Price = 39000m,
                            ProductTypeId = 1,
                            Size = "40",
                            Stock = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(518),
                            Description = "Ürün Kodu:\r\n4XRHDZTX8",
                            ImageUrl = "/images/product/AKesim3.1.webp",
                            ImageUrl2 = "/images/product/AKesim3.2.webp",
                            ImageUrl3 = "/images/product/AKesim3.3.webp",
                            IsDeleted = false,
                            Name = "A Kesim Straplez Gelinlik",
                            Price = 41000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(520),
                            Description = "HARPER\r\nÜrün Kodu:\r\n4XLLSMS251246|IVORY_40",
                            ImageUrl = "/images/product/AKesim4.1.webp",
                            ImageUrl2 = "/images/product/AKesim4.2.webp",
                            ImageUrl3 = "/images/product/AKesim4.3.webp",
                            IsDeleted = false,
                            Name = "Fiyonk Askılı Kalp Yaka A Kesim Gelinlik",
                            Price = 41000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(522),
                            Description = "CERES\r\nÜrün Kodu:\r\n1019|KEMİK_36",
                            ImageUrl = "/images/product/AKesim5.1.webp",
                            ImageUrl2 = "/images/product/AKesim5.2.webp",
                            ImageUrl3 = "/images/product/AKesim5.3.webp",
                            IsDeleted = false,
                            Name = "İnce Askılı Payet İşlemeli A Kesim Gelinlik",
                            Price = 41000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(524),
                            Description = "ELORA\r\nÜrün Kodu:\r\n4XLWPD30838|BRDL IV/IV_38",
                            ImageUrl = "/images/product/AKesim6.1.webp",
                            ImageUrl2 = "/images/product/AKesim6.2.webp",
                            ImageUrl3 = "/images/product/AKesim6.3.webp",
                            IsDeleted = false,
                            Name = "Kuyruklu Saten A Kesim Gelinlik",
                            Price = 41000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(526),
                            Description = "Ürün Kodu:\r\nSWGHBFHD38",
                            ImageUrl = "/images/product/balık1.1.webp",
                            ImageUrl2 = "/images/product/balık1.2.webp",
                            ImageUrl3 = "/images/product/balık1.3.webp",
                            IsDeleted = false,
                            Name = "V Yaka Balık Model Gelinlik",
                            Price = 42000m,
                            ProductTypeId = 1,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(529),
                            Description = "Ürün Kodu:\r\nSWG970|SOLID/IV_38",
                            ImageUrl = "/images/product/balık2.1.webp",
                            ImageUrl2 = "/images/product/balık2.2.webp",
                            ImageUrl3 = "/images/product/balık2.3.webp",
                            IsDeleted = false,
                            Name = "Straplez Balık ModelGelinlik",
                            Price = 43000m,
                            ProductTypeId = 1,
                            Size = "40",
                            Stock = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(531),
                            Description = "Ürün Kodu:\r\nSWFHFHHGS38",
                            ImageUrl = "/images/product/balık3.1.webp",
                            ImageUrl2 = "/images/product/balık3.2.webp",
                            ImageUrl3 = "/images/product/balık3.3.webp",
                            IsDeleted = false,
                            Name = "Straplez Balık Model Gelinlik",
                            Price = 44000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(533),
                            Description = "Ürün Kodu:\r\n997|KEMİK_38",
                            ImageUrl = "/images/product/balık4.1.webp",
                            ImageUrl2 = "/images/product/balık4.2.webp",
                            ImageUrl3 = "/images/product/balık4.3.webp",
                            IsDeleted = false,
                            Name = "Sırt Dekolteli Balık Model Gelinlik",
                            Price = 44000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(535),
                            Description = "Ürün Kodu:\r\n1006|KEMİK_38\r\n",
                            ImageUrl = "/images/product/balık5.1.webp",
                            ImageUrl2 = "/images/product/balık5.2.webp",
                            ImageUrl3 = "/images/product/balık5.3.webp",
                            IsDeleted = false,
                            Name = "İnce Askılı Dantel Detaylı Balık Model Gelinlik",
                            Price = 44000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(537),
                            Description = "BEGONIA\r\nÜrün Kodu:\r\n4XLSWG897|IVORY/BISQ_40",
                            ImageUrl = "/images/product/balık6.1.webp",
                            ImageUrl2 = "/images/product/balık6.2.webp",
                            ImageUrl3 = "/images/product/balık6.3.webp",
                            IsDeleted = false,
                            Name = "Askılı Kuyruklu Balık Model Gelinlik",
                            Price = 44000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(539),
                            Description = "AMELIE\r\nÜrün Kodu:\r\n1028|KEMİK_40",
                            ImageUrl = "/images/product/helen1.1.webp",
                            ImageUrl2 = "/images/product/helen1.2.webp",
                            ImageUrl3 = "/images/product/helen1.3.webp",
                            IsDeleted = false,
                            Name = "Derin Yırtmaçlı Sırt Detaylı Gelinlik",
                            Price = 35000m,
                            ProductTypeId = 1,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(541),
                            Description = "CAMILLA\r\nÜrün Kodu:\r\n1020|KEMİK_40",
                            ImageUrl = "/images/product/helen2.1.webp",
                            ImageUrl2 = "/images/product/helen2.2.webp",
                            ImageUrl3 = "/images/product/helen2.3.webp",
                            IsDeleted = false,
                            Name = "V Yaka Payet İşlemeli Gelinlik",
                            Price = 36000m,
                            ProductTypeId = 1,
                            Size = "40",
                            Stock = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(543),
                            Description = "EDITH\r\nÜrün Kodu:\r\n1029|KEMİK_40",
                            ImageUrl = "/images/product/helen3.1.webp",
                            ImageUrl2 = "/images/product/helen3.2.webp",
                            ImageUrl3 = "/images/product/helen3.3.webp",
                            IsDeleted = false,
                            Name = "Düşük Omuzlu Büzgülü Kol Detaylı Gelinlik",
                            Price = 37000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(545),
                            Description = "LISA\r\nÜrün Kodu:\r\n1023|KEMİK_40",
                            ImageUrl = "/images/product/helen4.1.webp",
                            ImageUrl2 = "/images/product/helen4.2.webp",
                            ImageUrl3 = "/images/product/helen4.3.webp",
                            IsDeleted = false,
                            Name = "İnce Askılı Düşük Omuz Tül Detaylı Gelinlik",
                            Price = 37000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(547),
                            Description = "BLUEBELL\r\nÜrün Kodu:\r\n4XLWPD31711|IVORY_40",
                            ImageUrl = "/images/product/helen5.1.webp",
                            ImageUrl2 = "/images/product/helen5.2.webp",
                            ImageUrl3 = "/images/product/helen5.3.webp",
                            IsDeleted = false,
                            Name = "Straplez Tül Dantel İşlemeli Gelinlik",
                            Price = 37000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 4,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(550),
                            Description = "Ürün Kodu:\r\n4XLWPD24633|IVORY_42",
                            ImageUrl = "/images/product/helen6.1.webp",
                            ImageUrl2 = "/images/product/helen6.2.webp",
                            ImageUrl3 = "/images/product/helen6.3.webp",
                            IsDeleted = false,
                            Name = "Payet İşlemeli Sırtı İpli Pırıltılı Gelinlik",
                            Price = 37000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(551),
                            Description = "Gelinlik\r\nÜrün Kodu:\r\n4XLSDWG1052|SOFT WHITE_40",
                            ImageUrl = "/images/product/Modern1.1.webp",
                            ImageUrl2 = "/images/product/Modern1.2.webp",
                            ImageUrl3 = "/images/product/Modern1.3.webp",
                            IsDeleted = false,
                            Name = "Önü Kısa Arkası Uzun Krep Dar Kesim",
                            Price = 46000m,
                            ProductTypeId = 1,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(553),
                            Description = "HARMONIA\r\nÜrün Kodu:\r\n4XLWPD26986|IVORY_38",
                            ImageUrl = "/images/product/Modern2.1.webp",
                            ImageUrl2 = "/images/product/Modern2.2.webp",
                            ImageUrl3 = "/images/product/Modern2.3.webp",
                            IsDeleted = false,
                            Name = "Fiyonk Detaylı Saten Dar Kesim Gelinlik",
                            Price = 47000m,
                            ProductTypeId = 1,
                            Size = "40",
                            Stock = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(555),
                            Description = "CARINO\r\nÜrün Kodu:\r\n1017|KEMİK_40",
                            ImageUrl = "/images/product/Modern3.1.webp",
                            ImageUrl2 = "/images/product/Modern3.2.webp",
                            ImageUrl3 = "/images/product/Modern3.3.webp",
                            IsDeleted = false,
                            Name = "Boncuk İşlemeli Kuyruklu Gelinlik",
                            Price = 48000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(557),
                            Description = "LIZA\r\nÜrün Kodu:\r\n4XLSWG834|IVORY/C_40",
                            ImageUrl = "/images/product/Modern4.1.webp",
                            ImageUrl2 = "/images/product/Modern4.2.webp",
                            ImageUrl3 = "/images/product/Modern4.3.webp",
                            IsDeleted = false,
                            Name = "Düşük Omuz Detaylı Yırtmaçlı Gelinlik",
                            Price = 48000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(559),
                            Description = "PAULA\r\nÜrün Kodu:\r\n4XLWPD23641|IVORY_44",
                            ImageUrl = "/images/product/Modern5.1.webp",
                            ImageUrl2 = "/images/product/Modern5.2.webp",
                            ImageUrl3 = "/images/product/Modern5.3.webp",
                            IsDeleted = false,
                            Name = "Kayık Yaka Mikado Gelinlik",
                            Price = 48000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 5,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(561),
                            Description = "PRIYANKA\r\nÜrün Kodu:\r\n4XLWGIN RI 0135|IVORY_34",
                            ImageUrl = "/images/product/Modern6.1.webp",
                            ImageUrl2 = "/images/product/Modern6.2.webp",
                            ImageUrl3 = "/images/product/Modern6.3.webp",
                            IsDeleted = false,
                            Name = "Sırtı Degaje Detaylı Dar Kesim Gelinlik",
                            Price = 48000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(563),
                            Description = "Ürün Kodu:\r\nMA-B5625-001-INF|A29_0",
                            ImageUrl = "/images/product/nikah1.1.webp",
                            ImageUrl2 = "/images/product/nikah1.2.webp",
                            ImageUrl3 = "/images/product/nikah1.3.webp",
                            IsDeleted = false,
                            Name = "Yırtmaçlı Midi Boy Jarse Nikah Elbisesi",
                            Price = 31000m,
                            ProductTypeId = 1,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(565),
                            Description = "Ürün Kodu:\r\nVC5595WHT|IVORY_34",
                            ImageUrl = "/images/product/nikah2.1.webp",
                            ImageUrl2 = "/images/product/nikah2.2.webp",
                            ImageUrl3 = "/images/product/nikah2.3.webp",
                            IsDeleted = false,
                            Name = "Arkası Yırtmaçlı Balon Kol Detaylı Gelinlik",
                            Price = 32000m,
                            ProductTypeId = 1,
                            Size = "40",
                            Stock = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(567),
                            Description = "Ürün Kodu:\r\nVC5592WHT|IVORY_34",
                            ImageUrl = "/images/product/nikah3.1.webp",
                            ImageUrl2 = "/images/product/nikah3.2.webp",
                            ImageUrl3 = "/images/product/nikah3.3.webp",
                            IsDeleted = false,
                            Name = "Fiyonk Detaylı Yırtmaçlı Krep Gelinlik",
                            Price = 33000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(570),
                            Description = "KITO\r\nÜrün Kodu:\r\n4XLSDWG1175|SOFT WHITE_44",
                            ImageUrl = "/images/product/nikah4.1.webp",
                            ImageUrl2 = "/images/product/nikah4.2.webp",
                            ImageUrl3 = "/images/product/nikah4.3.webp",
                            IsDeleted = false,
                            Name = "Askılı V Yaka Yırtmaçlı Krep Kumaş Gelinlik",
                            Price = 33000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(572),
                            Description = "Ürün Kodu:\r\n4XLGS290018WHT|IVORY_42",
                            ImageUrl = "/images/product/nikah5.1.webp",
                            ImageUrl2 = "/images/product/nikah5.2.webp",
                            ImageUrl3 = "/images/product/nikah5.3.webp",
                            IsDeleted = false,
                            Name = "Tek Omuz Yırtmaçlı Saten Uzun Gelinlik",
                            Price = 33000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 6,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(574),
                            Description = "BERYL\r\nÜrün Kodu:\r\n4XLF15554WHT|IVORY_38",
                            ImageUrl = "/images/product/nikah6.1.webp",
                            ImageUrl2 = "/images/product/nikah6.2.webp",
                            ImageUrl3 = "/images/product/nikah6.3.webp",
                            IsDeleted = false,
                            Name = "Kalın Askılı Mini Nikah Elbisesi",
                            Price = 33000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(576),
                            Description = " ÜRÜN KODU: 34066 700GG",
                            ImageUrl = "/images/product/prenses1.1.webp",
                            ImageUrl2 = "/images/product/prenses1.2.webp",
                            ImageUrl3 = "/images/product/prenses1.3.webp",
                            IsDeleted = false,
                            Name = "Dantel İşlemeli Straplez Balo Tipi Kuyruklu Gelinlik",
                            Price = 49000m,
                            ProductTypeId = 1,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(578),
                            Description = " ÜRÜN KODU: 34067 701GG",
                            ImageUrl = "/images/product/prenses2.1.webp",
                            ImageUrl2 = "/images/product/prenses2.2.webp",
                            ImageUrl3 = "/images/product/prenses2.3.webp",
                            IsDeleted = false,
                            Name = "İnci İşlemeli Askılı A Kesim Gelinlik",
                            Price = 50000m,
                            ProductTypeId = 1,
                            Size = "40",
                            Stock = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(580),
                            Description = " ÜRÜN KODU: 34068 702GG",
                            ImageUrl = "/images/product/prenses3.1.webp",
                            ImageUrl2 = "/images/product/prenses3.2.webp",
                            ImageUrl3 = "/images/product/prenses3.3.webp",
                            IsDeleted = false,
                            Name = "Saten Dantel İşlemeli V Yaka Gelinlik",
                            Price = 51000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(581),
                            Description = " ÜRÜN KODU: 34069 703GG",
                            ImageUrl = "/images/product/prenses4.1.webp",
                            ImageUrl2 = "/images/product/prenses4.2.webp",
                            ImageUrl3 = "/images/product/prenses4.3.webp",
                            IsDeleted = false,
                            Name = "Çiçek Desenli Prenses Gelinlik",
                            Price = 52000m,
                            ProductTypeId = 1,
                            Size = "42",
                            Stock = 5,
                            UserId = 0
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(584),
                            Description = "ÜRÜN KODU: 34070 704GG",
                            ImageUrl = "/images/product/prenses5.1.webp",
                            ImageUrl2 = "/images/product/prenses5.2.webp",
                            ImageUrl3 = "/images/product/prenses5.3.webp",
                            IsDeleted = false,
                            Name = "Dantel İşlemeli Kısa Kollu Gelinlik",
                            Price = 53000m,
                            ProductTypeId = 1,
                            Size = "44",
                            Stock = 1,
                            UserId = 0
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 7,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(586),
                            Description = ",ÜRÜN KODU: 34071 705GG",
                            ImageUrl = "/images/product/prenses6.1.webp",
                            ImageUrl2 = "/images/product/prenses6.2.webp",
                            ImageUrl3 = "/images/product/prenses6.3.webp",
                            IsDeleted = false,
                            Name = "Fiyonklu Derin Dekolteli Gelinlik",
                            Price = 54000m,
                            ProductTypeId = 1,
                            Size = "46",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(588),
                            Description = "FRANCESCA\r\nÜrün Kodu:\r\n4XLWPD30119|IVORY/OLEG_42",
                            ImageUrl = "/images/product/uzunk1.1.webp",
                            ImageUrl2 = "/images/product/uzunk1.2.webp",
                            ImageUrl3 = "/images/product/uzunk1.3.webp",
                            IsDeleted = false,
                            Name = "Düşük Omuzlu Uzun Kollu Dar Kesim Gelinlik",
                            Price = 34000m,
                            ProductTypeId = 1,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(590),
                            Description = "NORA\r\nÜrün Kodu:\r\n4XLMS251270|IVORY/STON_40",
                            ImageUrl = "/images/product/uzunk2.1.webp",
                            ImageUrl2 = "/images/product/uzunk2.2.webp",
                            ImageUrl3 = "/images/product/uzunk2.3.webp",
                            IsDeleted = false,
                            Name = "Uzun Kollu Dar Kesim Gelinlik",
                            Price = 35000m,
                            ProductTypeId = 1,
                            Size = "40",
                            Stock = 2,
                            UserId = 0
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(592),
                            Description = "VALENTINA\r\nÜrün Kodu:\r\n4XLWPD30203|IVORY/N N_42",
                            ImageUrl = "/images/product/uzunk3.1.webp",
                            ImageUrl2 = "/images/product/uzunk3.2.webp",
                            ImageUrl3 = "/images/product/uzunk3.3.webp",
                            IsDeleted = false,
                            Name = "Uzun Kollu Işıltılı Tül Dar Kesim Gelinlik",
                            Price = 36000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(594),
                            Description = "CARINA\r\nÜrün Kodu:\r\n4XLWPD29555|IVORY_40",
                            ImageUrl = "/images/product/uzunk4.1.webp",
                            ImageUrl2 = "/images/product/uzunk4.2.webp",
                            ImageUrl3 = "/images/product/uzunk4.3.webp",
                            IsDeleted = false,
                            Name = "Uzun Tül Kollu V Yaka Krep Dar Kesim Gelinlik",
                            Price = 36000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(596),
                            Description = "AMORETTE\r\nÜrün Kodu:\r\n4XLWPD30117|IVORY/OLEG_38",
                            ImageUrl = "/images/product/uzunk5.1.webp",
                            ImageUrl2 = "/images/product/uzunk5.2.webp",
                            ImageUrl3 = "/images/product/uzunk5.3.webp",
                            IsDeleted = false,
                            Name = "Dantel İşlemeli Uzun Kollu A Kesim Gelinlik",
                            Price = 36000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 8,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(598),
                            Description = "PRIYA\r\nÜrün Kodu:\r\n4XLWPD30295|SOFT WHITE_38",
                            ImageUrl = "/images/product/uzunk6.1.webp",
                            ImageUrl2 = "/images/product/uzunk6.2.webp",
                            ImageUrl3 = "/images/product/uzunk6.3.webp",
                            IsDeleted = false,
                            Name = "Uzun Tül Kollu Krep Dar Kesim Gelinlik",
                            Price = 36000m,
                            ProductTypeId = 1,
                            Size = "36",
                            Stock = 4,
                            UserId = 0
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(600),
                            Description = "Buket 1 Aksesuar, ÜRÜN KODU: 45001 800AK",
                            ImageUrl = "/images/product/b1.1.webp",
                            ImageUrl2 = "/images/product/b1.2.webp",
                            ImageUrl3 = "/images/product/b1.3.webp",
                            IsDeleted = false,
                            Name = "GRAND MAGNOLIA",
                            Price = 2000m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 10,
                            UserId = 0
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(602),
                            Description = "Buket 2 Aksesuar, ÜRÜN KODU: 45002 801AK",
                            ImageUrl = "/images/product/b2.1.webp",
                            ImageUrl2 = "/images/product/b2.2.webp",
                            ImageUrl3 = "/images/product/b2.3.webp",
                            IsDeleted = false,
                            Name = "GLORIA",
                            Price = 2500m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 8,
                            UserId = 0
                        },
                        new
                        {
                            Id = 51,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(603),
                            Description = "Buket 3 Aksesuar, ÜRÜN KODU: 45003 802AK",
                            ImageUrl = "/images/product/b3.1.webp",
                            ImageUrl2 = "/images/product/b3.2.webp",
                            ImageUrl3 = "/images/product/b3.3.webp",
                            IsDeleted = false,
                            Name = "ECROU",
                            Price = 3000m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 6,
                            UserId = 0
                        },
                        new
                        {
                            Id = 52,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(605),
                            Description = "Buket 4 Aksesuar, ÜRÜN KODU: 45004 803AK",
                            ImageUrl = "/images/product/b4.1.webp",
                            ImageUrl2 = "/images/product/b4.2.webp",
                            ImageUrl3 = "/images/product/b4.3.webp",
                            IsDeleted = false,
                            Name = "SPRING",
                            Price = 2200m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 12,
                            UserId = 0
                        },
                        new
                        {
                            Id = 53,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(607),
                            Description = "Buket 5 Aksesuar, ÜRÜN KODU: 45005 804AK",
                            ImageUrl = "/images/product/b5.1.webp",
                            ImageUrl2 = "/images/product/b5.2.webp",
                            ImageUrl3 = "/images/product/b5.3.webp",
                            IsDeleted = false,
                            Name = "MÜRDÜM",
                            Price = 2700m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 9,
                            UserId = 0
                        },
                        new
                        {
                            Id = 54,
                            CategoryId = 9,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(609),
                            Description = "Buket 6 Aksesuar, ÜRÜN KODU: 45006 805AK",
                            ImageUrl = "/images/product/b6.1.webp",
                            ImageUrl2 = "/images/product/b6.2.webp",
                            ImageUrl3 = "/images/product/b6.3.webp",
                            IsDeleted = false,
                            Name = "V E L V E T",
                            Price = 2900m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 7,
                            UserId = 0
                        },
                        new
                        {
                            Id = 55,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(612),
                            Description = "Ürün Kodu:\r\nWPD27227|IVORY_U",
                            ImageUrl = "/images/product/duvak1.1.webp",
                            ImageUrl2 = "/images/product/duvak1.2.webp",
                            ImageUrl3 = "/images/product/duvak1.3.webp",
                            IsDeleted = false,
                            Name = "Dantel ve Pul İşlemeli Katedral Boy Gelin Duvağı",
                            Price = 1500m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 10,
                            UserId = 0
                        },
                        new
                        {
                            Id = 56,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(614),
                            Description = "Ürün Kodu:\r\nINCILIDUVAKV2|IVORY_U",
                            ImageUrl = "/images/product/duvak2.1.webp",
                            ImageUrl2 = "/images/product/duvak2.2.webp",
                            ImageUrl3 = "/images/product/duvak2.3.webp",
                            IsDeleted = false,
                            Name = "Uzun Tül Tamamı İnci Detaylı Duvak",
                            Price = 2000m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 8,
                            UserId = 0
                        },
                        new
                        {
                            Id = 57,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(616),
                            Description = "Ürün Kodu:\r\nWPD28215V2|IVORY_U",
                            ImageUrl = "/images/product/duvak3.1.webp",
                            ImageUrl2 = "/images/product/duvak3.2.webp",
                            ImageUrl3 = "/images/product/duvak3.3.webp",
                            IsDeleted = false,
                            Name = "Taş İşlemeli Kısa Duvak",
                            Price = 2500m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 6,
                            UserId = 0
                        },
                        new
                        {
                            Id = 58,
                            CategoryId = 10,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(618),
                            Description = "Ürün Kodu:\r\nV1810B|IVORY_U",
                            ImageUrl = "/images/product/duvak4.1.webp",
                            ImageUrl2 = "/images/product/duvak4.2.webp",
                            ImageUrl3 = "/images/product/duvak4.3.webp",
                            IsDeleted = false,
                            Name = "Çiçek Motif Dantel İşlemeli Tül Gelin Duvağı",
                            Price = 2500m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 6,
                            UserId = 0
                        },
                        new
                        {
                            Id = 59,
                            CategoryId = 11,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(620),
                            Description = "Ürün Kodu:\r\nVGR191101001|IVORY_U",
                            ImageUrl = "/images/product/tac1.1.webp",
                            ImageUrl2 = "/images/product/tac1.2.webp",
                            ImageUrl3 = "/images/product/tac1.3.webp",
                            IsDeleted = false,
                            Name = "Kırık Beyaz İncili Gelin Tacı",
                            Price = 1700m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 7,
                            UserId = 0
                        },
                        new
                        {
                            Id = 60,
                            CategoryId = 11,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(621),
                            Description = "Ürün Kodu:\r\nH42235|SILVER_U",
                            ImageUrl = "/images/product/tac2.1.webp",
                            ImageUrl2 = "/images/product/tac2.2.webp",
                            ImageUrl3 = "/images/product/tac2.3.webp",
                            IsDeleted = false,
                            Name = "Yapay Elmas Gelin Tacı",
                            Price = 2100m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 8,
                            UserId = 0
                        },
                        new
                        {
                            Id = 61,
                            CategoryId = 11,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(623),
                            Description = "Ürün Kodu:\r\nWPD20601|IVORY_U",
                            ImageUrl = "/images/product/tac3.1.webp",
                            ImageUrl2 = "/images/product/tac3.2.webp",
                            ImageUrl3 = "/images/product/tac3.3.webp",
                            IsDeleted = false,
                            Name = "İnci Detaylı Yapay Elmas Gelin Tacı",
                            Price = 200m,
                            ProductTypeId = 2,
                            Size = "Standart",
                            Stock = 6,
                            UserId = 0
                        },
                        new
                        {
                            Id = 62,
                            CategoryId = 12,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(625),
                            Description = "ÜRÜN KODU : 35060 206G",
                            ImageUrl = "/images/product/1.1.jpg",
                            ImageUrl2 = "/images/product/1.2.jpg",
                            ImageUrl3 = "/images/product/1.3.jpg",
                            IsDeleted = false,
                            Name = "SEDEF SATEN BLOOM GELİN AYAKKABISI",
                            Price = 2850m,
                            ProductTypeId = 3,
                            Size = "36",
                            Stock = 6,
                            UserId = 0
                        },
                        new
                        {
                            Id = 63,
                            CategoryId = 12,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(627),
                            Description = "ÜRÜN KODU : 35060 0250G\r\n",
                            ImageUrl = "/images/product/2.1.jpg",
                            ImageUrl2 = "/images/product/2.2.jpg",
                            ImageUrl3 = "/images/product/2.3.jpg",
                            IsDeleted = false,
                            Name = "SEDEF SATEN FLORENCE MİNİ TOPUK GELİN AYAKKABISI\r\n",
                            Price = 4500m,
                            ProductTypeId = 3,
                            Size = "37",
                            Stock = 9,
                            UserId = 0
                        },
                        new
                        {
                            Id = 64,
                            CategoryId = 12,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(629),
                            Description = "ÜRÜN KODU : 34210 2233G",
                            ImageUrl = "/images/product/3.1.jpg",
                            ImageUrl2 = "/images/product/3.2.jpg",
                            ImageUrl3 = "/images/product/3.3.jpg",
                            IsDeleted = false,
                            Name = "SEDEF NİNA İNCE TOPUK GELİN AYAKKABISI\r\n",
                            Price = 4500m,
                            ProductTypeId = 3,
                            Size = "38",
                            Stock = 3,
                            UserId = 0
                        },
                        new
                        {
                            Id = 65,
                            CategoryId = 12,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(631),
                            Description = "ÜRÜN KODU : 35072 1159G\r\n",
                            ImageUrl = "/images/product/4.1.jpg",
                            ImageUrl2 = "/images/product/4.2.jpg",
                            ImageUrl3 = "/images/product/4.3.jpg",
                            IsDeleted = false,
                            Name = "SEDEF SATEN LEROY TEK BANT GELİN AYAKKABISI\r\n",
                            Price = 2250m,
                            ProductTypeId = 3,
                            Size = "39",
                            Stock = 7,
                            UserId = 0
                        },
                        new
                        {
                            Id = 66,
                            CategoryId = 12,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(633),
                            Description = "ÜRÜN KODU : 34066 700GG\r\n",
                            ImageUrl = "/images/product/5.1.jpg",
                            ImageUrl2 = "/images/product/5.2.jpg",
                            ImageUrl3 = "/images/product/5.3.jpg",
                            IsDeleted = false,
                            Name = "SEDEF SO VERA GELİN AYAKKABISI\r\n",
                            Price = 4500m,
                            ProductTypeId = 3,
                            Size = "40",
                            Stock = 6,
                            UserId = 0
                        },
                        new
                        {
                            Id = 67,
                            CategoryId = 12,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(634),
                            Description = "ÜRÜN KODU : 35060 202G\r\n",
                            ImageUrl = "/images/product/6.1.jpg",
                            ImageUrl2 = "/images/product/6.2.jpg",
                            ImageUrl3 = "/images/product/6.3.jpg",
                            IsDeleted = false,
                            Name = "SEDEF SATEN BLOOM GELİN AYAKKABISI\r\n",
                            Price = 2850m,
                            ProductTypeId = 3,
                            Size = "41",
                            Stock = 7,
                            UserId = 0
                        });
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.ProductSaleDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SaleId");

                    b.ToTable("ProductSaleDetails");
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 891, DateTimeKind.Local).AddTicks(9990),
                            IsDeleted = false,
                            Name = "Gow"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(4),
                            IsDeleted = false,
                            Name = "Accessory"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 7, 20, 13, 24, 53, 892, DateTimeKind.Local).AddTicks(6),
                            IsDeleted = false,
                            Name = "Shoe"
                        });
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Product", b =>
                {
                    b.HasOne("BelleMariee.App.Entity.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelleMariee.App.Entity.Entities.ProductType", null)
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.ProductSaleDetails", b =>
                {
                    b.HasOne("BelleMariee.App.Entity.Entities.Product", "Product")
                        .WithMany("ProductSalesDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelleMariee.App.Entity.Entities.Sale", "ProductSale")
                        .WithMany("ProductSalesDetails")
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductSale");
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Sale", b =>
                {
                    b.HasOne("BelleMariee.App.Entity.Entities.Customer", "Customer")
                        .WithMany("ProductSales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("BelleMariee.App.DataAccess.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("BelleMariee.App.DataAccess.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("BelleMariee.App.DataAccess.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("BelleMariee.App.DataAccess.Identity.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BelleMariee.App.DataAccess.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("BelleMariee.App.DataAccess.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Customer", b =>
                {
                    b.Navigation("ProductSales");
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Product", b =>
                {
                    b.Navigation("ProductSalesDetails");
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BelleMariee.App.Entity.Entities.Sale", b =>
                {
                    b.Navigation("ProductSalesDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
